# This config is meant for local development only

[WebAPI]
  bind = "localhost"  # avoids macOS firewall confirmation!
  port = "8080"

[gigawallet]
  dogecoind = "mainnet"  # which dogecoind to connect to

[dogecoind.testnet]
  host    = "localhost"
  zmqport = 28332
  rpcport = 44555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"

[dogecoind.mainnet]
  host    = "192.168.1.41"
  zmqport = 28332
  rpchost = "192.168.1.41"
  rpcport = 22555
  rpcpass = "suchpay"
  rpcuser = "suchpay"

[loggers.events]
  path = "./events.log"
  types = ["ALL"]
