# This config is meant for local development only

[WebAPI]
  adminbind = "localhost"  # avoids macOS firewall confirmation!
  adminport = "8081"
  pubbind = "localhost"  # avoids macOS firewall confirmation!
  pubport = "8082"
  pubapirooturl = "http://localhost:8082"

[gigawallet]
  network = "mainnet"  # which dogecoind to connect to

[dogecoind.testnet]
  host    = "localhost"
  zmqport = 28332
  rpcport = 44555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"

[dogecoind.mainnet]
  host    = "127.0.0.1"
  zmqport = 28332
  rpchost = "127.0.0.1"
  rpcport = 22555
  rpcpass = "suchpay"
  rpcuser = "suchpay"

## Setup loggers, see pkg/config.go LoggersConfig
[loggers.events]
  path = "./events.log"
  types = ["ALL"]

## Setup http Callbacks, see pkg/config.go CallbackConfig

#[callbacks.example1]
#  path = "https://example.com/invoiceEvents"
#  types = ["INV"]


## Setup MQTT event publishing, see pkg/config.go MQTTConfig

#[mqtt]
#  address = "test.mosquitto.org:1884"
#  username = "rw"
#  password = "readwrite"
#  clientid = "gigawallet"
#
#[mqtt.queues.accounts]
#  topicfilter = "account"
#  Types = ["ACC"]
