# This config is meant for local development only

[WebAPI]
  bind = "192.168.1.25"  # avoids macOS firewall confirmation!
  port = "8081"

[gigawallet]
  network = "mainnet"  # which dogecoind to connect to

[dogecoind.testnet]
  host    = "localhost"
  zmqport = 28332
  rpcport = 44555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"

[dogecoind.mainnet]
  host    = "127.0.0.1"
  zmqport = 28332
  rpchost = "127.0.0.1"
  rpcport = 22555
  rpcpass = "suchpay"
  rpcuser = "suchpay"

[loggers.events]
  path = "./events.log"
  types = ["ALL"]
