# This config is meant for local development only

[gigawallet]
  dogecoind = "testnet"  # which dogecoind to connect to

[dogecoind.testnet]
  host    = "localhost"
  zmqport = 28332
  rpcport = 44555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"

[dogecoind.mainnet]
  host    = "localhost"
  zmqport = 28332
  rpcport = 22555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"
