# This config is meant for local development only

[gigawallet]
  dogecoind = "testnet"  # which dogecoind to connect to

[dogecoind.testnet]
  rpcaddr = "localhost"
  rpcport = 44555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"

[dogecoind.mainnet]
  rpcaddr = "localhost"
  rpcport = 22555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"
